# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: jiesneboor Blog
subtitle: You can you BiBi
description:
author: jiesenboor
language: zh-Hans
timezone:

#头像
avatar: /imgs/avatar.png

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://jiesenboor.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: 
- other/*
- other/demo/photoviewer/*
- other/demo/photoviewer/photoviewer/*

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
	编程: programming
	生活: life
	其它: other
	博客: blog
	写作: writing
tag_map:
	博客: blog
	写作: writing
# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/jiesenboor/jiesenboor.github.io.git
  branch: master
  message: commit...

#多说分享，这个功能必须与多说评论同时使用
duoshuo_share: true
#多说评论
duoshuo_shortname: jiesenboor
#swiftype搜索: https://swiftype.com/home
swiftype_key: Qz27t2QcoCx9AdRovT4n

auto_excerpt:
	enalbe: true
	length: 100
